Repository Contabilone/emites-server-api-docs, pull requests merged in 2020-05, with the labels that each got.

#6 Mapping vlAliquotaICMSOperacaoAnterior
  source/includes/_fields_api.md
Labels: documentation

#7 Documented name attribute in the create user endpoint
  source/includes/_users.md
Labels: review

#9 Update tax calculator doc to only accept single request
  source/includes/_tax_calculator.md
Labels: documentation

#10 Update 'lista_autorizacao' attribute message
  source/includes/_fields_api.md
Labels: documentation

#11 #173001425 :: Corrige campo email para admin_email
  source/includes/_accounts.md
Labels: bug

#8 Fix server url and authentication method
  source/includes/_accounts.md
  source/includes/_authorize_batch.md
  source/includes/_authorize_single.md
  source/includes/_basic_information.md
  source/includes/_batch_emission.md
  source/includes/_cancel_note.md
  source/includes/_cfe_storage.md
  source/includes/_consult_note.md
  source/includes/_correction_note.md
  source/includes/_disabled_note.md
  source/includes/_document_numerations.md
  source/includes/_hybrid_emission.md
  source/includes/_list_notes.md
  source/includes/_organizations.md
  source/includes/_single_emission.md
  source/includes/_tax_calculator.md
  source/includes/_users.md
Labels: bug, review

#12 Revert tax calculator doc to only accept batch request
  source/includes/_tax_calculator.md
Labels: bug, documentation

#14 Add an observation about synchronicity in BA and SP
  source/includes/_fields_api.md
Labels: bug, documentation

#13 Add admin_name attribute to account create
  source/includes/_accounts.md
Labels: enhancement, review
