Repository Contabilone/emites-server-api-docs, pull requests merged in 2021-03, with the labels that each got.

#24 Additions to taxation rules import
  source/includes/_taxation_rules_import.md
Labels: documentation, review

#31 New condition and consequence attributes in taxation rules import
  source/includes/_fields_api.md
  source/includes/_taxation_rules_import.md
Labels: review

#33 Update gems
  Gemfile.lock
Labels: enhancement

#34 Update gems
  Gemfile
  Gemfile.lock
Labels: enhancement

#35 Fix for view without menu
  Gemfile
  Gemfile.lock
  config.rb
  source/stylesheets/_normalize.scss
Labels: bug
